### ISSUE TITLE
Unable to Control more than one animation using slider in Godot

### ISSUE THREAD

**Issue by cakh** [Masterarbeit-haptische-Handschuhe/kraft-vr-gloves#1]
Für die HiWi-Arbeit verscuhte ich die einzelnen Fingern in Godot mit Sliders zu steuern (wie in [Link](https://akhilrajca.itch.io/hand-bend-unity)). Leider funktioniert es nicht.
Zuerst habe ich probiert, ein AnimationPlayer zu erstellen, in dem es verschiedene Animationen gibt, wie IndexBend, MiddleBend usw.  Da ich mit dem AnimationPlayer das nicht schaffen konnte, habe ich eine Frage in Godot-Webseite gepostet ([Link](https://godotengine.org/qa/108419/animationplayer-play-anim2-automatically-plays-anim1?show=108514#a108514)). 

Danach habe ich für jede Animation, eine einzelne AnimationPlayer erstellt. Mit einer Skript verscuhte ich die gewünchte Animation mit Slidern zu steuern. Das Problem: nur noch kann nur eine Animation mit Slidern gesteuert werden. Ich habe ein Video von meinem Blidschirm aufgenommen, das ganua das Problem zeigt (Masterarbeit/HiWi/Problem_Godot_Multiple_Animations.mp4). Die folgende Schritte habe ich gemacht:

- Das Skript HandBend.gd in AnimationPlayer CloseAnim hingefügt. Mit "Close" Slider funktioniert die Animation
- Das Skript vom CloseAnim gelöcht
- Das Skript HandBend.gd in AnimationPlayer IndexAnim hingefügt. Mit "Index" Slider funktioniert die Animation
- Das Skript HandBend.gd in AnimationPlayer CloseAnim und IndexAnim hingefügt. Mit "Close" Slider funktioniert die Animation **nicht** und mit "Index" Slider funktionert sie

Wenn das Skript auf mehr als eine AnimationPlayer hinzugefügt wird, kann die Animation nicht mehr gesteuert werden.

**Comment by pwab** [comment]
1. Warum erstellst du das Issue hier und nicht in https://github.com/Masterarbeit-haptische-Handschuhe/hiwi-stuff?
2. Hast du das Godot Projekt hier irgendwo schon hochgeladen? Ich hätte es hier erwartet: https://github.com/Masterarbeit-haptische-Handschuhe/hiwi-stuff
3. Wo ist der Pfad `Masterarbeit/HiWi/Problem_Godot_Multiple_Animations.mp4`? Ich konnte die Datei im Nextcloud nicht finden.

**Comment by cakh** [comment]
1. und 2. waren ein Fehler von meiner Seite! ich hatte alles im Ordner Masterarbeit hochgeladen. Ich habe ein neues Issue an der richtigen Stelle erstellt.
3. Der Pfad habe ich auch unter dem neuen Issue aktualisiert
